// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DetailRequest struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type DetailResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type AllCategoriesRequest struct {
	Unused               int32    `protobuf:"varint,1,opt,name=Unused,proto3" json:"Unused,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllCategoriesRequest) Reset()         { *m = AllCategoriesRequest{} }
func (m *AllCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*AllCategoriesRequest) ProtoMessage()    {}
func (*AllCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *AllCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllCategoriesRequest.Unmarshal(m, b)
}
func (m *AllCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *AllCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllCategoriesRequest.Merge(m, src)
}
func (m *AllCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_AllCategoriesRequest.Size(m)
}
func (m *AllCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllCategoriesRequest proto.InternalMessageInfo

func (m *AllCategoriesRequest) GetUnused() int32 {
	if m != nil {
		return m.Unused
	}
	return 0
}

type AllCategoriesResponse struct {
	Categories           []*ProductCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AllCategoriesResponse) Reset()         { *m = AllCategoriesResponse{} }
func (m *AllCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*AllCategoriesResponse) ProtoMessage()    {}
func (*AllCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *AllCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllCategoriesResponse.Unmarshal(m, b)
}
func (m *AllCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *AllCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllCategoriesResponse.Merge(m, src)
}
func (m *AllCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_AllCategoriesResponse.Size(m)
}
func (m *AllCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllCategoriesResponse proto.InternalMessageInfo

func (m *AllCategoriesResponse) GetCategories() []*ProductCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CategoryProductsRequest struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryProductsRequest) Reset()         { *m = CategoryProductsRequest{} }
func (m *CategoryProductsRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryProductsRequest) ProtoMessage()    {}
func (*CategoryProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *CategoryProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryProductsRequest.Unmarshal(m, b)
}
func (m *CategoryProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryProductsRequest.Marshal(b, m, deterministic)
}
func (m *CategoryProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryProductsRequest.Merge(m, src)
}
func (m *CategoryProductsRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryProductsRequest.Size(m)
}
func (m *CategoryProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryProductsRequest proto.InternalMessageInfo

func (m *CategoryProductsRequest) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type CategoryProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CategoryProductsResponse) Reset()         { *m = CategoryProductsResponse{} }
func (m *CategoryProductsResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryProductsResponse) ProtoMessage()    {}
func (*CategoryProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *CategoryProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryProductsResponse.Unmarshal(m, b)
}
func (m *CategoryProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryProductsResponse.Marshal(b, m, deterministic)
}
func (m *CategoryProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryProductsResponse.Merge(m, src)
}
func (m *CategoryProductsResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryProductsResponse.Size(m)
}
func (m *CategoryProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryProductsResponse proto.InternalMessageInfo

func (m *CategoryProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type SearchRequest struct {
	SearchTerm           string   `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Categories           []uint64 `protobuf:"varint,2,rep,packed,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

func (m *SearchRequest) GetCategories() []uint64 {
	if m != nil {
		return m.Categories
	}
	return nil
}

type SearchResponse struct {
	SearchResults        []*Product `protobuf:"bytes,1,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{7}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetSearchResults() []*Product {
	if m != nil {
		return m.SearchResults
	}
	return nil
}

type Product struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Manufacturer         string   `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string   `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Price                int64    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{8}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Product) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductCategory struct {
	CategoryId           uint64   `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductCategory) Reset()         { *m = ProductCategory{} }
func (m *ProductCategory) String() string { return proto.CompactTextString(m) }
func (*ProductCategory) ProtoMessage()    {}
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{9}
}

func (m *ProductCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCategory.Unmarshal(m, b)
}
func (m *ProductCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCategory.Marshal(b, m, deterministic)
}
func (m *ProductCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCategory.Merge(m, src)
}
func (m *ProductCategory) XXX_Size() int {
	return xxx_messageInfo_ProductCategory.Size(m)
}
func (m *ProductCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCategory.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCategory proto.InternalMessageInfo

func (m *ProductCategory) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *ProductCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*DetailRequest)(nil), "catalog.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "catalog.DetailResponse")
	proto.RegisterType((*AllCategoriesRequest)(nil), "catalog.AllCategoriesRequest")
	proto.RegisterType((*AllCategoriesResponse)(nil), "catalog.AllCategoriesResponse")
	proto.RegisterType((*CategoryProductsRequest)(nil), "catalog.CategoryProductsRequest")
	proto.RegisterType((*CategoryProductsResponse)(nil), "catalog.CategoryProductsResponse")
	proto.RegisterType((*SearchRequest)(nil), "catalog.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "catalog.SearchResponse")
	proto.RegisterType((*Product)(nil), "catalog.Product")
	proto.RegisterType((*ProductCategory)(nil), "catalog.ProductCategory")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0x7c, 0xc0, 0x04, 0x87, 0xb2, 0x4a, 0xdb, 0x55, 0x24, 0x8a, 0xbb, 0xa7, 0x08,
	0xa1, 0x1c, 0xc2, 0x01, 0x84, 0x38, 0x80, 0x5a, 0x09, 0x72, 0x2b, 0x86, 0xde, 0x90, 0x2a, 0x63,
	0x0f, 0xad, 0x85, 0xbf, 0xd8, 0x5d, 0x1f, 0xf2, 0x73, 0xf8, 0x33, 0xfc, 0x2e, 0x94, 0xf5, 0x78,
	0x63, 0x27, 0x34, 0x48, 0xdc, 0xbc, 0x6f, 0xde, 0xbc, 0x79, 0x33, 0x3b, 0x6b, 0xf0, 0xa2, 0x50,
	0x87, 0x69, 0x71, 0xbb, 0x28, 0x65, 0xa1, 0x0b, 0x36, 0xa2, 0xa3, 0x38, 0x07, 0xef, 0x12, 0x75,
	0x98, 0xa4, 0x01, 0xfe, 0xac, 0x50, 0x69, 0x76, 0x04, 0xae, 0xfa, 0x51, 0x71, 0xc7, 0x77, 0xe6,
	0x0f, 0x83, 0xcd, 0xa7, 0x78, 0x0b, 0x93, 0x86, 0xa2, 0xca, 0x22, 0x57, 0xc8, 0x9e, 0xc3, 0xa8,
	0x94, 0x45, 0x5c, 0x45, 0xda, 0xf0, 0xc6, 0xcb, 0xa3, 0x45, 0x23, 0x7f, 0x55, 0xe3, 0x41, 0x43,
	0x10, 0x0b, 0x98, 0xbe, 0x4f, 0xd3, 0x8b, 0x50, 0xe3, 0x6d, 0x21, 0x13, 0x54, 0x4d, 0x9d, 0x13,
	0x18, 0x5e, 0xe7, 0x95, 0xc2, 0xd8, 0x48, 0x0c, 0x02, 0x3a, 0x89, 0x4f, 0x70, 0xbc, 0xc3, 0xa7,
	0xa2, 0xaf, 0x01, 0x22, 0x8b, 0x72, 0xc7, 0x77, 0xe7, 0xe3, 0x25, 0xdf, 0xad, 0x4b, 0x79, 0xeb,
	0xa0, 0xc5, 0x15, 0x6f, 0xe0, 0xb4, 0xc1, 0x89, 0x66, 0x5d, 0x3c, 0x83, 0x31, 0x11, 0xd7, 0x37,
	0x49, 0x6d, 0xa5, 0x6f, 0x73, 0xd7, 0xab, 0x58, 0x7c, 0x04, 0xbe, 0x9f, 0x4b, 0x8e, 0x5e, 0xc0,
	0x03, 0xea, 0xb2, 0xf1, 0xb3, 0x3f, 0x07, 0xcb, 0x10, 0x57, 0xe0, 0x7d, 0xc6, 0x50, 0x46, 0x77,
	0xad, 0xda, 0xca, 0x00, 0x37, 0x1a, 0x65, 0x46, 0x13, 0x87, 0x1a, 0xfa, 0x82, 0x32, 0x63, 0x67,
	0x9d, 0x8e, 0x7b, 0xbe, 0xdb, 0xf2, 0xb6, 0xe9, 0x6b, 0x05, 0x93, 0x46, 0x91, 0x1c, 0xbd, 0x82,
	0x09, 0x49, 0x4a, 0x54, 0x55, 0x7a, 0xc0, 0x97, 0xa7, 0x9a, 0xcc, 0x0d, 0x4d, 0xfc, 0x72, 0x60,
	0x44, 0xa1, 0xfd, 0x0d, 0x60, 0x0c, 0xfa, 0x79, 0x98, 0x21, 0xef, 0x19, 0xc8, 0x7c, 0x33, 0x1f,
	0xc6, 0x31, 0xaa, 0x48, 0x26, 0xa5, 0x4e, 0x8a, 0x9c, 0xbb, 0x26, 0xd4, 0x86, 0x98, 0x80, 0x47,
	0x59, 0x98, 0x57, 0xdf, 0xc3, 0x48, 0x57, 0x12, 0x25, 0xef, 0x1b, 0x4a, 0x07, 0x63, 0x53, 0x18,
	0x64, 0x45, 0x8c, 0x29, 0x1f, 0x98, 0x60, 0x7d, 0xd8, 0xa0, 0xa5, 0x4c, 0x22, 0xe4, 0x43, 0xdf,
	0x99, 0xbb, 0x41, 0x7d, 0x10, 0x77, 0xf0, 0x78, 0xe7, 0x96, 0xff, 0x79, 0x7d, 0xff, 0xe7, 0x7c,
	0xf9, 0xbb, 0x07, 0xa3, 0x8b, 0x7a, 0x60, 0xec, 0x12, 0x9e, 0x7c, 0x40, 0x4d, 0x85, 0xeb, 0x77,
	0xa0, 0xd8, 0x89, 0x9d, 0x67, 0xe7, 0xf1, 0xcc, 0x4e, 0xf7, 0x70, 0xba, 0x98, 0x6b, 0x98, 0x6e,
	0x55, 0xb6, 0xcb, 0xcd, 0x9e, 0xda, 0x84, 0xbf, 0x3d, 0x92, 0xd9, 0xd9, 0x7d, 0x61, 0x92, 0xfd,
	0x0a, 0xc7, 0x5b, 0x59, 0xb5, 0xca, 0xed, 0x60, 0x7c, 0x9b, 0x78, 0xcf, 0xe6, 0xcf, 0xce, 0x0f,
	0x30, 0x48, 0xfd, 0x1d, 0x78, 0x84, 0xd5, 0x6b, 0xd6, 0x6a, 0xbb, 0xb3, 0xc9, 0xad, 0xb6, 0xbb,
	0xfb, 0xf8, 0x6d, 0x68, 0xfe, 0x36, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x19, 0xe1,
	0x91, 0x7e, 0x04, 0x00, 0x00,
}
