// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: warehouse.proto

package warehouse

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Warehouse service

type WarehouseService interface {
	GetWarehouseDetails(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error)
}

type warehouseService struct {
	c    client.Client
	name string
}

func NewWarehouseService(name string, c client.Client) WarehouseService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "warehouse"
	}
	return &warehouseService{
		c:    c,
		name: name,
	}
}

func (c *warehouseService) GetWarehouseDetails(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error) {
	req := c.c.NewRequest(c.name, "Warehouse.GetWarehouseDetails", in)
	out := new(DetailsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Warehouse service

type WarehouseHandler interface {
	GetWarehouseDetails(context.Context, *DetailsRequest, *DetailsResponse) error
}

func RegisterWarehouseHandler(s server.Server, hdlr WarehouseHandler, opts ...server.HandlerOption) error {
	type warehouse interface {
		GetWarehouseDetails(ctx context.Context, in *DetailsRequest, out *DetailsResponse) error
	}
	type Warehouse struct {
		warehouse
	}
	h := &warehouseHandler{hdlr}
	return s.Handle(s.NewHandler(&Warehouse{h}, opts...))
}

type warehouseHandler struct {
	WarehouseHandler
}

func (h *warehouseHandler) GetWarehouseDetails(ctx context.Context, in *DetailsRequest, out *DetailsResponse) error {
	return h.WarehouseHandler.GetWarehouseDetails(ctx, in, out)
}
